version: '3.8'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      - DB_NAME=garagesDB
      - COLLECTION_NAME=garages
      - PORT=9000
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - app    

volumes:
  mongodb_data: